### Review PR
POST http://localhost:8000/review
Content-Type: application/json

{
  "owner": "josueaponte7",
  "repo": "codereview-ai-agent",
  "pr_number": 4
}

### Historial de revisiones
GET http://localhost:8000/reviews/josueaponte7/codereview-ai-agent